### ISSUE TITLE
Initial port to Backdrop

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/conditional_fields#1]
This is underway but still in early stages. Feel free to add to the list or comments below.

 - [x] Find all references to saving an `id` for field instances and make sure it uses the new format (since Backdrop doesn't save a unique numeric id for instances): `entity_type.bundle.field_name`

**Comment by laryn** [comment]
Status: preliminary testing after the latest commit shows the basic admin UI for configuring the module seems to be working as expected (but file an issue if you find something I missed) but we're not seeing the actual conditional functionality working yet, e.g. on the node create/edit page.

**Comment by laryn** [comment]
More progress but can't figure out why this is not firing:
https://github.com/backdrop-contrib/conditional_fields/blob/1.x-3.x/conditional_fields.module#L427-L429

Once we solve that I think we'll be very close. But i have to set this aside for now.

**Comment by bradbulger** [comment]
in conditional_fields_element_after_build(), the key in $form_state should be 'complete_form' not 'complete form'

**Comment by laryn** [comment]
@bradbulger That opens up some things... Thanks!

**Comment by laryn** [comment]
Not seeing anything in the watchdog on basic tests at this point... but not seeing it working either!

**Comment by laryn** [comment]
Closing this as outdated with the pre-release of 1.x-3.0.0. 
https://github.com/backdrop-contrib/conditional_fields/releases

Please open new issues for anything you run into while testing/using.
