### ISSUE TITLE
Conditional fields on user entity not working -- possibly b/c sql query conversion incomplete?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/conditional_fields#10]
I've been unable to get conditional fields to work on the user entity in Backdrop, though my testing on Drupal 7 shows that the same configuration works okay.

As best I can tell, the problem stems from `conditional_fields_load_dependencies()` when the dependencies are supposed to be limited by entity_type or bundle. It appears the code there has been commented out, because the Drupal 7 way of adding this limit was to join to the `field_config_instance` table, which has been removed from Backdrop. 

In order to do the same thing in Backdrop, we could add an `entity_type` and `bundle` column directly to the `conditional_fields` database table. When an entry is made into this table, we can record the `entity_type` and `bundle` along with each condition.  Then, when executing this query, all we should need to do is add a `WHERE` clause for entity and/or bundle.

**We will also need to include an upgrade path for those coming from Drupal 7**. The addition of these columns will need to be done early in the core upgrade process, before the `field_config_instance` table has been deleted. 

This problem could also be fixed by https://github.com/backdrop-contrib/conditional_fields/issues/7. We could save the `entity_type` and `bundle` into the config file at the time the files are written (for the upgrade path, this would still need to be done early in the core upgrade process, before the `field_config_instance` table has been deleted.)

**Comment by jenlampton** [comment]
I started working on this, but now I think I want to go the #7 route instead.  I'm going to try that first.

**Comment by laryn** [comment]
I'll be honest, this port was (is) a bit of a staggering attempt and I don't think I've even tested on user accounts at all. 😳 Yes, I agree with the idea to focus on #7 first to see if that solves it.

**Comment by laryn** [comment]
@jenlampton Just to be sure, are you using the `'alpha-1` tag or the latest dev? The only difference being this commit, I think:

https://github.com/backdrop-contrib/conditional_fields/commit/0832b67d10032edc682b808b479511a3d3f9e0ef

**Comment by laryn** [comment]
I just did a quick test on the latest dev and it seems to be working. Please reopen if you are still having an issue.
