### ISSUE TITLE
Module doesn't work?

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/conditional_fields#11]
Using latest 1.19.0 version of Backdrop and cannot get this module to work. Have tried many combinations of fields but nothing appears to work at all. Not seeing any console errors. For clarification I'm trying to get a field to appear/disappear when a checkbox is checked in the node create/edit form.

I've seen the issue regarding fieldsets, but I haven't made any changes to the node edit template so not sure how this effects me, or indeed how to solve the issue. A good number of the fields in the node edit form don't have a fieldset wrapper, and so if this is the default behaviour with Backdrop core it would indicate this module is fatally flawed.

**Comment by laryn** [comment]
@sbgraphicdesign Until we get traction on that core issue, I think you will need to put the fields that you want to show/hide with this module within a fieldset (using the Field Group module). It's not ideal and not considered final form, obviously, but is a workaround for now.

**Comment by sbgraphicdesign** [comment]
Thanks for that. Could I suggest you add this crucial bit of information to the Read Me? Possibly even make Field Group module a dependency?

**Comment by laryn** [comment]
Great idea, thanks!

I've updated the README to link to this wiki page:
https://github.com/backdrop-contrib/conditional_fields/wiki/Field-Group-workaround

(If you get a chance to document the process feel free to update that page)
