### ISSUE TITLE
Conditions have no affect

### ISSUE THREAD

**Issue by allsite** [backdrop-contrib/conditional_fields#13]
A basic condition "Test is invisible when New Player? has value "1"." has no affect. I've tried other combinations and have yet to see any action on the form fire while using core field types. It would be great if this module worked, supported reference fields and unlike D7 would properly enforce required/optional status.

**Comment by laryn** [comment]
Hi @allsite ! 

Did you happen to see the note in the README about the known issue which links to this wiki page?
https://github.com/backdrop-contrib/conditional_fields/wiki/Field-Group-workaround

**Comment by allsite** [comment]
Thank you for the fast reply @laryn! I can confirm the conditions do fire while inside a field group. It's not a terrible work-around.
