### ISSUE TITLE
Page on backdropcms.org / availability through installer?

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/conditional_fields#2]
Thank you so much for working on a port of this module! It's an important one for the kinds of sites I help people build (digital humanities projects). I was wondering if there's something standing in the way of the module having a module page on backdropcms.org and/or being available through the Backdrop module installer UI? I'm rewriting "Drupal for Humanists" for Backdrop, and I'd like to link to a backdropcms.org page for this module if possible. Thank you!

**Comment by laryn** [comment]
@quinnanya The reason there's no Backdrop module page or entry in the installer is because I haven't made an official release yet. I started this since I will need it for a coming project and wanted to get it off the ground so others might be able to help out if they needed it, too. 

If you're willing to help me test, I'll try to focus on this port next week when I'm back by my desk and see if we can get a formal release soon.

**Comment by quinnanya** [comment]
@laryn Ahh, so that's how it works! Thanks for the explanation.

Happy to help test! Is there a list of things I should work from, or just install the current version and try to break it, given the limitations you've mentioned (e.g. only using core fields as trigger fields)?

**Comment by laryn** [comment]
@quinnanya I think I need to get it a step or two further before I ask you to test, unfortunately! I'll tag you again when it's ready for testing.

**Comment by laryn** [comment]
@quinnanya Are you able to install the latest dev on a fresh site and do some basic testing and filing of issues?

**Comment by quinnanya** [comment]
@laryn Sure! Can work on it tonight.

**Comment by quinnanya** [comment]
@laryn Just filed #4 -- error message upon installation. Do you want me to keep testing, or is that error likely to have more repercussions so I should wait on it?

**Comment by laryn** [comment]
@quinnanya No, I'll take a look at that one first. 😳

**Comment by bradbulger** [comment]
Just tried installing this, and in the field configuration UI, it looks like it is grabbing the first field widget for the node, not the field involved in the dependency. (I am not sure whether the field whose values should be available is the "dependent" or the "dependee", both of those words sound like they describe the field which depends on the other field.)

**Comment by laryn** [comment]
@bradbulger I agree, those terms are confusing at first. Would it be clearer to say "Conditional field" instead of "Dependent" and use "Depends on" instead of "Dependee"?

Hoping to make progress on this module early this month... 🤞

**Comment by quinnanya** [comment]
@laryn I like that wording tweak -- I always had some trial and error trying to remember which field was which in Drupal.

**Comment by laryn** [comment]
@bradbulger I just pushed a change that should take care of the issue you mention above.  Both you and @quinnanya should feel free to open new issues as you find them. It's still a WIP, of course, but getting closer.

**Comment by bradbulger** [comment]
I don't have good ideas on single words, I always have to spell it out verbosely in my mind.
Also, in case you haven't run into these yet, I've been trying to work with `#states` in custom code and ran into some core issues, [3495](https://github.com/backdrop/backdrop-issues/issues/3495) and [3489](https://github.com/backdrop/backdrop-issues/issues/3489), working with node forms.

**Comment by laryn** [comment]
Ah, good to know. If you want to install the latest dev and take a gander at why this may not be firing, I'd appreciate any insight!
https://github.com/backdrop-contrib/conditional_fields/issues/1#issuecomment-459808695

I'll come back to this later and will keep an eye on those two core issues you raised. Thanks!

**Comment by stpaultim** [comment]
This project was listed as `ready in contrib` on https://backdropcms.org/upgrade-from-drupal/top-100-drupal-7-modules.

Someone reported this here:
https://github.com/backdrop/backdrop-issues/issues/4359

I changed it to `underway in contrib.`

I'm not missing anything, am I?

**Comment by laryn** [comment]
As soon as the core issue is resolved (assuming that solves #5 as well) I think we're ready for an initial release, so just waiting on that core bug to be fixed.

**Comment by laryn** [comment]
This module is still listed as a beta release but is available through the Project Installer, so I'm going to close this issue.
