### ISSUE TITLE
No hook_config_info() - cannot update config

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/conditional_fields#27]
This is holding up all config updates. Either add `hook_config_info()` or delete the config file -- since it's empty perhaps the latter is the better option.

**Comment by herbdool** [comment]
@laryn there's no conditional_fields.settings so no need for the file. This will fix config imports. But people might still have the file in their staging so they'll have to remove it manually.

**Comment by laryn** [comment]
@herbdool I wrapped this into https://github.com/backdrop-contrib/conditional_fields/issues/7 so if you get a chance to test that, look for this fix there as well.
