### ISSUE TITLE
Undefined array key "profile"

### ISSUE THREAD

**Issue by theflightrs** [backdrop-contrib/conditional_fields#33]
Edit: Content retracted, copied to [Fields Visibility Condition queue](https://github.com/backdrop-contrib/field_visibility_condition/issues/7)

**Comment by laryn** [comment]
Is this filed in the wrong issue queue? The error looks to be from ‘ field_visibility_condition’.

As a separate comment, perhaps you could instead set a css class based on this profile field value so you don’t have to add fields twice, and just style them differently based on that css class?

**Comment by theflightrs** [comment]
@laryn Wow, i just checked and you are right. Sorry for that - i really mixed them up. Will remove it soon!

Actually, i'm not sure how to do that yet, but i have two CSS classes.  I will try to think about that. 

The website is a bit of complex interplay of distinguishing between anonymous, unauthorized and authorized users since it's more of a game website. It's a bit of a brain breaker here how to show the blocks straightforwardly, but i'm leaving it at white for now:

![2024-11-11 01 12 47 www 5sd org 65323744774d](https://github.com/user-attachments/assets/554ad772-cb07-431e-a8b6-1fbc89728566)

![2024-11-11 01 13 19 www 5sd org b95482b1c952](https://github.com/user-attachments/assets/23385a30-694e-4815-b8d7-8ecec12b9989)

![2024-11-11 12 36 43 www 5sd org 459aef53b1ac](https://github.com/user-attachments/assets/7f8bca33-028e-47fb-b095-f3647c5d8f71)

Edit: Feel free to erase this issue, i will head over to the respective queue.

**Comment by laryn** [comment]
Looks like an interesting project! :)

**Comment by theflightrs** [comment]
@laryn Thanks, i hope to introduce it somewhere on the BD forums at some point. 5SD Operations Center, quite wild!
