### ISSUE TITLE
Syntax error message when enabling conditional fields

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/conditional_fields#4]
Installed Backdrop 1.11.3 on MAMP 5.1 with default settings (PHP 7.2.8, MySQL 5.7.23). Conditional fields was the first module I added, but when I tried to enable it, I got the "website has encountered an error" message, and this in the log:

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL COMMENT 'The id of the dependee field instance.', `dependent` VARCHAR ' at line 3: CREATE TABLE {conditional_fields} ( `id` INT NOT NULL auto_increment COMMENT 'The primary identifier for a dependency.', `dependee` VARCHAR NOT NULL COMMENT 'The id of the dependee field instance.', `dependent` VARCHAR NOT NULL COMMENT 'The id of the dependent field instance.', `options` LONGBLOB NOT NULL COMMENT 'Serialized data containing the options for the dependency.', PRIMARY KEY (`id`) ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 ROW_FORMAT=DYNAMIC COMMENT 'Stores dependencies between fields.'; Array ( ) in db_create_table() (line 2795 of /Applications/MAMP/htdocs/backdropconditional/core/includes/database/database.inc).

**Comment by laryn** [comment]
@quinnanya I disabled and uninstalled, then reinstalled and don't see this but will try on a completely fresh install.

**Comment by laryn** [comment]
@quinnanya I just installed on a fresh Backdrop site (using Lando locally) and didn't run into this. I wonder if the latest commit I made in https://github.com/backdrop-contrib/conditional_fields/issues/3 could possibly have made a difference or if it is something specific to MAMP or your setup. (My Lando defaulted to MySQL 5.7.24 and PHP 7.0.32.)

**Comment by quinnanya** [comment]
A bit more fiddling:

1. Installing Backdrop on Pantheon (PHP 7.1), I'm able to install and enable the module successfully. I tried installing it via the "manual install" (in the UI) and pasting the link to the Github zip file.

2. Trying again locally on a fresh site on MAMP, I went to install it again via the "manual install" in the UI, the same way, but got an error before it even installed: "The info file (temporary://update-extraction-f93a505c/conditional_fields-1.x-3.x/tests/conditional_fields_test.tests.info) does not define a 'type' attribute." I tried changing the MAMP version of PHP from 7.2 to 7.1, and that didn't seem to fix it.

**Comment by laryn** [comment]
@quinnanya Interesting. I have not touched the tests yet but it's curious that that is throwing an error like that. I will try to fire up MAMP and do an install and some testing there as soon as I get a chance (but that might not be today).

**Comment by quinnanya** [comment]
@laryn For another data point, I tried in a shared hosting environment, PHP 7.0, MySQL 5.7.24. Got the same error message about the info file.

**Comment by laryn** [comment]
It sounds quite similar to this:
https://github.com/backdrop/backdrop-issues/issues/3447

Do you have core updates turned on on the sites that give the error?

Also related, perhaps:
https://github.com/backdrop/backdrop-issues/issues/1294

L.

**Comment by laryn** [comment]
@quinnanya Regarding the `.tests.info` error, you could try this patch and report back there:
https://github.com/backdrop/backdrop-issues/issues/1294

**Comment by laryn** [comment]
@quinnanya The patch linked above was merged. If you have a chance to test on the most recent version of Backdrop could you report back here?

**Comment by laryn** [comment]
Closing as outdated. Please reopen if necessary.
