### ISSUE TITLE
List field dependee with list field dependents only works when fields are in individual fieldsets

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/conditional_fields#5]
Have this set up on a content type that has a term reference field as the dependee, and 16 fields that are dependent upon it based on which selection is made. Each field becomes visible when the dependee field has a corresponding selection. So if 'Topic A' is checked in the dependee field, then the 'Topic A Subfield' displays. At first I thought this simply was not working, but then by accident I discovered that it does work, so long as each individual field is placed within a fieldset. So 'Topic A Subfield' needs to be in its own fieldset, 'Topic B Subfield' needs to be in its own fieldset, etc.

This is on Backdrop 1.13.2 with Field Group v1.x-1.0.4 installed. I have not tested in a vanilla build of Backdrop, so this module could very well be conflicting with another module. But wanted to post this here at the moment of discovery in case anyone else is coming across a similar issue. I'll try to post more after I have tested with no other modules present.

**Comment by laryn** [comment]
@kelizoliva Thanks for the report! This looks helpful -- I've been porting this module sporadically but haven't actually needed it or used it myself yet. I'll try to look at this when I'm back by the computer later this month, but feel free to submit a PR or any further debugging info you find in the meantime to help speed things along.

**Comment by kelizoliva** [comment]
What I have is working for now for this particular project; I will be able to test more in a couple of weeks when my workload calms down a bit. I'll test some more and see if I can debug it myself, and submit a PR if I can figure it out.

**Comment by oadaeh** [comment]
I believe this is related to https://github.com/backdrop/backdrop-issues/issues/3489
I tried to modify the code in the module to take into account that issue, but I only got worse behavior. I didn't spend very long at it, however, because I had already been debugging it for several hours and was finally able to get what I needed done by directly modifying the field in a form alter function.

**Comment by laryn** [comment]
This should be solved with the merge of https://github.com/backdrop/backdrop-issues/issues/5157

I'm setting `1.20.3` as the required version of core from this point.
