### ISSUE TITLE
CSS: very long field names make admin tables hard to use

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/conditional_fields#8]
I have an "Other" text field on my site that needs to be displayed when a select value has its value set to "Other". The label for my text field is `Where do you live if the country is not in the list above? `, which is long enough that it breaks the table formatting on `admin/structure/dependencies`. 

I recommend that we set a max-width on select lists in the table, so that the table remains usable regardless of the length of field labels.

**Comment by laryn** [comment]
Seems reasonable -- can you include a screenshot?
